# Config file for Dosbox-Staging 0.82.0 

[sdl]
fullscreen=false
fullresolution=desktop
windowresolution=1280x960
output=opengl
texture_renderer=auto
priority=higher higher
mapperfile=mapper.map

[dosbox]
machine=svga_s3
memsize=32
mcb_fault_strategy=deny
vmemsize=auto

[render]
aspect=true
monochrome_palette=green
glshader=sharp
integer_scaling=auto

[composite]
composite=auto
era=auto
hue=0
saturation=100
contrast=100
brightness=0
convergence=0

[voodoo]
#                    voodoo: Enable 3dfx Voodoo emulation (enabled by default).
#            voodoo_memsize: Set the amount of video memory for 3dfx Voodoo graphics, either 4 or 12 megabytes.
#                            The memory is used by the Frame Buffer Interface (FBI) and Texture Mapping Unit (TMU)
#                            as follows:
#                               4: 2 MB for the FBI and one TMU with 2 MB (default)
#                              12: 4 MB for the FBI and two TMUs, each with 4 MB.
#                            Possible values: 4, 12.
#            voodoo_threads: Use threads to improve 3dfx Voodoo performance:
#                              auto:     Use up to 8 threads based on available CPU cores (default).
#                              <value>:  Set a specific number of threads between 1 and 16.
#                            Note: Tests show that frame rates increase up to 8 threads after which
#                              they level off or decrease, in general.
# voodoo_bilinear_filtering: Use bilinear filtering to emulate the 3dfx Voodoo's texture
#                            smoothing effect. Only suggested if you have a fast desktop-class
#                            CPU, as it can impact frame rates on slower systems (disabled by default).

voodoo=true
voodoo_memsize=4
voodoo_threads=auto
voodoo_bilinear_filtering=false

[cpu]
core=auto
cputype=auto
cpu_cycles=3000
cpu_cycles_protected=auto
cpu_throttle=true

[mouse]
mouse_capture=onclick
mouse_middle_release=true
mouse_multi_display_aware=true
mouse_sensitivity=100
mouse_raw_input=true
#dos_mouse_driver notes: Disable if you intend to use original MOUSE.COM driver in emulated DOS.
dos_mouse_driver=true
dos_mouse_immediate=false
ps2_mouse_model=intellimouse
com_mouse_model=wheel+msm

[mixer]
rate=48000

[midi]
mididevice=auto

[fluidsynth]
soundfont=.\mt32\SoundCanvas.sf2

[mt32]
romdir=.\mt32

[sblaster]
sbtype=sb16
sbmixer=true
#sb_filter possible values: auto, sb1, sb2, sbpro1, sbpro2, sb16, modern (default), off.
sb_filter=modern
#oplmode possible values: auto, opl2, dualopl2, opl3, opl3gold, esfm, none. 
#Note: Original Adlib card emulated by using sbtype=none and oplmode=opl2
oplmode=auto
cms=auto

[gus]
gus=false
ultradir=C:\ULTRASND

[imfc]
# IBM Music Feature Card
imfc=false

[innovation]
#sidmodel possible values: auto, 6581, 8580, none.
sidmodel=none

[speaker]
#pcspeaker possible values: impulse (default), discrete, none, off.
pcspeaker=impulse
tandy=auto
#lpt_dac possible values: none, disney, covox, ston1, off
lpt_dac=none
ps1audio=false

[reelmagic]
reelmagic=off
reelmagic_key=auto
reelmagic_fcode=0

[joystick]
joysticktype=auto
timed=true
autofire=false
circularinput=false
deadzone=10
use_joy_calibration_hotkeys=false
joy_x_calibration=auto
joy_y_calibration=auto

[serial]
serial1=dummy
phonebookfile=phonebook.txt

[dos]
xms=true
ems=true
umb=true
ver=5.0

[ipx]
ipx=false

[ethernet]
ne2000=false

[autoexec]
@echo off