# Config file for Dosbox-Staging 0.82.2 

[sdl]
fullscreen=false
fullresolution=desktop
windowresolution=1280x960
output=opengl
texture_renderer=auto
priority=higher higher
mapperfile=mapper.map

[dosbox]
machine=svga_s3
memsize=32
mcb_fault_strategy=deny
vmemsize=auto

[render]
aspect=true
glshader=sharp
integer_scaling=auto

[cpu]
core=auto
#cputype possible values: auto, 386, 386_fast, 386_prefetch, 486, pentium, pentium_mmx.
cputype=auto
cpu_cycles=30000
cpu_cycles_protected=auto
cpu_throttle=true

[mouse]
mouse_capture=onclick
mouse_middle_release=true
mouse_multi_display_aware=true
mouse_sensitivity=40
mouse_raw_input=true
#dos_mouse_driver notes: Disable if you intend to use original MOUSE.COM driver in emulated DOS.
dos_mouse_driver=true
dos_mouse_immediate=false
ps2_mouse_model=intellimouse
com_mouse_model=wheel+msm

[mixer]
rate=48000

[midi]
mididevice=fluidsynth

[fluidsynth]
soundfont=.\mt32\SoundCanvas.sf2

[sblaster]
sbtype=sb16
sbmixer=true
#sb_filter possible values: auto, sb1, sb2, sbpro1, sbpro2, sb16, modern (default), off.
sb_filter=modern
#oplmode possible values: auto, opl2, dualopl2, opl3, opl3gold, esfm, none. 
#Note: Original Adlib card emulated by using sbtype=none and oplmode=opl2
oplmode=auto
cms=auto

[gus]
gus=false
ultradir=C:\ULTRASND

[speaker]
#pcspeaker possible values: impulse (default), discrete, none, off.
pcspeaker=impulse

[reelmagic]
reelmagic=off
reelmagic_key=auto
reelmagic_fcode=0

[joystick]
joysticktype=auto
timed=true
autofire=false
circularinput=false
deadzone=10
use_joy_calibration_hotkeys=false
joy_x_calibration=auto
joy_y_calibration=auto

[serial]
serial1=dummy
phonebookfile=phonebook.txt

[dos]
xms=true
ems=true
umb=true
ver=5.0
file_locking=true

[ipx]
ipx=false

[ethernet]
ne2000=false

[autoexec]
path=C:\;z:\;c:\windows\;y:\dos;y:\
@echo off
