# This is the configuration file for DOSBox Staging (0.83.0).

[sdl]
fullscreen=off
fullscreen_mode=standard
window_size=1280x960
output=opengl
texture_renderer=auto
mapperfile=mapper.map

[dosbox]
machine=svga_s3
memsize=32
mcb_fault_strategy=repair
vmemsize=auto
vmem_delay=off
dos_rate=default
vesa_modes=compatible

[render]
aspect=auto
monochrome_palette=green
shader=sharp
integer_scaling=auto
viewport=fit
deinterlacing=off
image_adjustments=off

[composite]
composite=auto
era=auto
hue=0
convergence=0

[cpu]
core=auto
# cputype possible values: auto, 386, 386_fast, 386_prefetch, 486, pentium, pentium_mmx.
cputype=auto
cpu_cycles=3000
cpu_cycles_protected=auto
cpu_throttle=on

[voodoo]
voodoo=on
voodoo_memsize=4
voodoo_threads=auto
voodoo_bilinear_filtering=on

[mouse]
mouse_sensitivity=100,100
mouse_raw_input=on
# To use a real DOS mouse driver (e.g., MOUSE.COM or CTMOUSE.EXE), disable this flag (off)
builtin_dos_mouse_driver=on
builtin_dos_mouse_driver_move_threshold=1
builtin_dos_mouse_driver_options=
ps2_mouse_model=intellimouse
com_mouse_model=wheel+msm

[mixer]
rate=48000
blocksize=1024
prebuffer=25

[midi]
# 'port' (default) replaced auto. Possible values: port, mt32, soundcanvas, fluidsynth, none.
mididevice=port
mpu401=intelligent

[mt32]
romdir=.\mt32

[fluidsynth]
soundfont=.\mt32\SoundCanvas.sf2
soundfont_volume=100

[soundcanvas]
soundcanvas_model=auto

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=on
#sb_filter possible values: auto, sb1, sb2, sbpro1, sbpro2, sb16, modern (default), off.
sb_filter=modern
#oplmode possible values: auto, opl2, dualopl2, opl3, opl3gold, esfm, none/off. 
#Note: Original Adlib card emulated by using sbtype=none and oplmode=opl2
#      Only 'oplmode = esfm' is not enough to get ESS Enhanced FM music in games;
#      you'll also need to set 'sbtype = ess', or leave it auto with 'sbtype = ess'.
oplmode=auto
opl_fadeout=off
opl_remove_dc_bias=off
cms=auto

[gus]
gus=off
gusbase=240
gusirq=5
gusdma=3
ultradir=C:\ULTRASND

[imfc]
imfc=off
imfc_base=2a20
imfc_irq=3

[innovation]
innovation=off

[speaker]
#pcspeaker possible values: impulse (default), discrete, none, off.
pcspeaker=impulse
# tandy possible values: auto, on, psg, off.
tandy=auto
tandy_fadeout=off
# lpt_dac possible values: none, disney, covox, ston1
lpt_dac=none
ps1audio=off

[reelmagic]
reelmagic=off
reelmagic_key=auto
reelmagic_fcode=0

[joystick]
# joystick possible values: auto, 2axis, 4axis, 4axis_2, fcs, ch, hidden, disabled
# Note: Remember to reset DOSBox's mapperfile if you saved it earlier.
joysticktype=auto
timed=on
autofire=off
swap34=off
buttonwrap=off
circularinput=off
deadzone=10
use_joy_calibration_hotkeys=off
joy_x_calibration=auto
joy_y_calibration=auto

[serial]
serial1=dummy
phonebookfile=phonebook.txt

[dos]
xms=on
ems=on
umb=on
ver=5.0
pcjr_memory_config=expanded
file_locking=auto

[ipx]
ipx=off

[ethernet]
ne2000=off
nicbase=300
nicirq=3
macaddr=AC:DE:48:88:99:AA
tcp_port_forwards=
udp_port_forwards=

[webserver]
webserver_enabled=off
webserver_bind_address=127.0.0.1
webserver_port=8086

[autoexec]
@echo off